### ISSUE TITLE
Porting Caffe Models to FPGA 

### ISSUE THREAD

**Issue by ZeroCool11000** [Xilinx/RFNoC-HLS-NeuralNet#3]
Is it possible to easily export caffe models to FPGAs ?
Are there any converters, to do that ?

Best regards.

**Comment by ZeroCool11000** [comment]
It would be also nice to have some short codes as examples. 

Best regards.

**Comment by ejk43** [comment]
Let me refer you to this repo for now: https://github.com/hls-fpga-machine-learning/hls4ml

You can use keras models to generate HLS compatible code. I believe

**Comment by ejk43** [comment]
(whoops, hit enter too early)

... Not sure about time frame for caffe.

Anyway, I've been helping out with that hls4ml repo. Eventually I will update *this* repo to import hls4ml and use that for generation with some rfnoc wrappers

**Comment by ejk43** [comment]
Now that I think about it, I'll open an issue to port over hls4ml...

By the way, I'll also mention I believe something does exist to convert caffe models too hls, but I'm not sure where or if it's open source

**Comment by ZeroCool11000** [comment]
Thx and best regards.
